### PR TITLE
Update REPOs for frr

### PR DESCRIPTION
**Pull request by krishvoor**
This image updates the REPOS for frr

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

Updates the REPOS target, allowing the GHA actions to build the image

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by krishvoor** [comment]
cc: @josecastillolema @jtaleric ptal

**Comment by josecastillolema** [comment]
I was just filling it.
Please update the README also.

**Comment by krishvoor** [comment]
> I was just filling it. Please update the README also.

The README.md is updated, do you have anything specific in mind?

**Comment by josecastillolema** [comment]
> The README.md is updated, do you have anything specific in mind?

Nope, thats perfect, thanks!

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
