### PR TITLE
[Multi-arch] netpol-scraper

### PR DESCRIPTION
**Pull request by krishvoor**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [x] Documentation Update

## Description

This PR adds Dockerfile for netpol-scraper and publish multi-arch images

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by krishvoor** [comment]
Hi @mohit-sheth @dry923 @mukrishn - ptal

**Comment by krishvoor** [comment]
Built with UBI9 Base Image, please find attached the logs below
[netpol-scraper-multi-arch.log](https://github.com/cloud-bulldozer/images/files/15501948/netpol-scraper-multi-arch.log)

**Comment by mukrishn** [comment]
LGTM

**Review by dry923 — APPROVED** [review]
LGTM!

**Pull request merged**
